# Generated by Django 2.0.7 on 2018-11-30 12:37

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=mdeditor.fields.MDTextField(help_text='内容', max_length=20480, verbose_name='内容'),
        ),
    ]
