# Generated by Django 2.0.7 on 2018-11-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20181130_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='chinese_name',
            field=models.CharField(blank=True, help_text='标签中文名', max_length=32, null=True, verbose_name='标签中文名'),
        ),
        migrations.AddField(
            model_name='tag',
            name='desc',
            field=models.CharField(blank=True, help_text='标签描述', max_length=128, null=True, verbose_name='标签描述'),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, help_text='标签slug', unique=True, verbose_name='标签slug'),
        ),
    ]
